### ISSUE TITLE
Heroku Build Failing NODE_DEBUG=request

### ISSUE THREAD

**Issue by tjsail33** [bower/registry-client#21]
```javascript
> ./node_modules/bower/bin/bower install


       /tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/node_modules/request/lib/debug.js:4
           console.error('REQUEST %s', util.format.apply(util, arguments))
                                       ^
       ReferenceError: util is not defined
           at debug (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/node_modules/request/lib/debug.js:4:33)
           at Request.init (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/node_modules/request/request.js:118:3)
           at new Request (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/node_modules/request/request.js:105:8)
           at Function.request [as get] (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/node_modules/request/index.js:53:11)
           at RegistryClient.doRequest (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/lib/lookup.js:88:26)
           at /tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/lib/lookup.js:38:27
           at Cache.<anonymous> (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-registry-client/lib/util/Cache.js:53:20)
           at fs.js:207:20
           at OpenReq.Req.done (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:143:5)
           at OpenReq.done (/tmp/build_8d8dc34d55e24c3d01a3f3ce66cbf816/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:63:22)
```

**Comment by sheerun** [comment]
It's request issue, not registry-client
